# Generated by Django 5.1.6 on 2026-03-04 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('owner_hint', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('ringing', 'Ringing'), ('busy', 'Busy'), ('wrap_up', 'Wrap-Up'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_state_change', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('exotel', 'Exotel'), ('plivo', 'Plivo')], max_length=20)),
                ('provider_call_uuid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dialing', 'Dialing'), ('ringing', 'Ringing'), ('human_detected', 'Human Detected'), ('machine_detected', 'Machine Detected'), ('bridged', 'Bridged'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('wrap_up_deadline', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('transcript_url', models.URLField(blank=True)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='dialer.agentprofile')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='dialer.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CallDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('machine', 'Machine'), ('bad_number', 'Bad Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to='dialer.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('machine', 'Machine'), ('bad_number', 'Bad Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up')], max_length=32)),
                ('is_completed', models.BooleanField(default=False)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dial_state', to='dialer.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CRMSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='hubspot', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_sync_logs', to='dialer.callsession')),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'status', 'created_at'], name='dialer_crms_target_e5665e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status'], name='dialer_call_status_18c1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['created_at'], name='dialer_call_created_e72958_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['provider', 'provider_call_uuid'], name='dialer_call_provide_d5dea5_idx'),
        ),
    ]
