# Generated by Django 5.1.6 on 2026-03-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0002_campaign_queue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='dialer_camp_status_a7edfd_idx',
            old_name='dialer_camp_status_70cb14_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignlead',
            new_name='dialer_camp_campaig_3de7bb_idx',
            old_name='dialer_camp_campaig_0e7c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignlead',
            new_name='dialer_camp_campaig_c1466d_idx',
            old_name='dialer_camp_campaig_43c882_idx',
        ),
    ]
