# Generated by Django 5.1.6 on 2026-03-05

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialer", "0003_rename_dialer_camp_status_70cb14_idx_dialer_camp_status_a7edfd_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("exotel", "Exotel"), ("upload", "Upload")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("audio_file", models.FileField(blank=True, upload_to="dialer/recordings/")),
                ("external_audio_url", models.URLField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transcript_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("transcript_text", models.TextField(blank=True)),
                ("transcript_segments", models.JSONField(blank=True, default=list)),
                ("transcript_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_asset",
                        to="dialer.callsession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source", "created_at"], name="dialer_reco_source_e8c301_idx"),
                    models.Index(fields=["transcript_status", "created_at"], name="dialer_reco_transcr_8a7aa0_idx"),
                ],
            },
        ),
    ]

