# Generated by Django 5.1.6 on 2026-03-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0004_recordingasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recordingasset',
            new_name='dialer_reco_source_1a5ca4_idx',
            old_name='dialer_reco_source_e8c301_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingasset',
            new_name='dialer_reco_transcr_c8bcf0_idx',
            old_name='dialer_reco_transcr_8a7aa0_idx',
        ),
    ]
