# Generated by Django 5.1.6 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialer", "0005_rename_dialer_reco_source_e8c301_idx_dialer_reco_source_1a5ca4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calldisposition",
            name="hubspot_deal_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="calldisposition",
            name="hubspot_deal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="HubSpotIntegrationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("access_token", models.TextField(blank=True)),
                (
                    "deal_association_mode",
                    models.CharField(
                        choices=[("deal_id", "Deal ID"), ("deal_name", "Deal Name")],
                        default="deal_id",
                        max_length=16,
                    ),
                ),
                ("default_deal_id", models.CharField(blank=True, max_length=64)),
                ("default_deal_name", models.CharField(blank=True, max_length=255)),
                ("auto_sync_terminal_calls", models.BooleanField(default=True)),
                ("auto_sync_on_disposition", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
