# Generated by Django 5.1.6 on 2026-03-19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialer", "0006_hubspotintegrationsettings_and_disposition_deal_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone_e164",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in E.164 format (e.g., +14155552671).",
                        regex=r"^\+?[1-9]\d{1,14}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaignlead",
            name="last_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("connected", "Connected"),
                    ("no_answer", "No Answer"),
                    ("busy", "Busy"),
                    ("voicemail", "Voicemail"),
                    ("machine", "Machine"),
                    ("bad_number", "Bad Number"),
                    ("interested", "Interested"),
                    ("not_interested", "Not Interested"),
                    ("follow_up", "Follow Up"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("provider_call_uuid", "")),
                fields=("provider", "provider_call_uuid"),
                name="unique_provider_call_uuid",
            ),
        ),
    ]
