from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("agents/", views.list_agents, name="list-agents"),
    path("agents/<int:agent_id>/status/", views.update_agent_status, name="update-agent-status"),
    path("campaigns/", views.list_campaigns, name="list-campaigns"),
    path("campaigns/create/", views.create_campaign, name="create-campaign"),
    path("campaigns/<int:campaign_id>/", views.get_campaign, name="get-campaign"),
    path("campaigns/<int:campaign_id>/analytics/", views.campaign_analytics, name="campaign-analytics"),
    path("campaigns/<int:campaign_id>/queue/", views.campaign_queue, name="campaign-queue"),
    path("campaigns/<int:campaign_id>/timeline/", views.campaign_timeline, name="campaign-timeline"),
    path("campaigns/<int:campaign_id>/timeline/clear/", views.clear_campaign_timeline, name="clear-campaign-timeline"),
    path("campaigns/timeline/clear-all/", views.clear_all_campaign_timelines, name="clear-all-campaign-timelines"),
    path("campaigns/<int:campaign_id>/start/", views.start_campaign, name="start-campaign"),
    path("campaigns/<int:campaign_id>/pause/", views.pause_campaign, name="pause-campaign"),
    path("campaigns/<int:campaign_id>/resume/", views.resume_campaign, name="resume-campaign"),
    path("campaigns/<int:campaign_id>/stop/", views.stop_campaign, name="stop-campaign"),
    path(
        "campaigns/<int:campaign_id>/restart-from-first/",
        views.restart_campaign_from_first,
        name="restart-campaign-from-first",
    ),
    path("campaigns/<int:campaign_id>/dispatch/", views.dispatch_campaign, name="dispatch-campaign"),
    path("campaigns/<int:campaign_id>/tick/", views.campaign_tick, name="campaign-tick"),
    path(
        "campaigns/<int:campaign_id>/contacts/<int:lead_id>/remove/",
        views.remove_campaign_contact,
        name="remove-campaign-contact",
    ),
    path("leads/", views.list_leads, name="list-leads"),
    path("contacts/", views.list_contacts, name="list-contacts"),
    path("leads/next/", views.next_lead, name="next-lead"),
    path("leads/upload/", views.upload_leads_csv, name="upload-leads-csv"),
    path("leads/manual/", views.create_manual_leads, name="create-manual-leads"),
    path("call-logs/", views.list_call_logs, name="list-call-logs"),
    path("call-logs/sync/exotel/", views.sync_exotel_call_logs, name="sync-exotel-call-logs"),
    path(
        "call-logs/<int:call_id>/trigger_transcription/",
        views.trigger_transcription,
        name="trigger-transcription",
    ),
    path("calls/start/exotel/", views.start_exotel_call, name="start-exotel-call"),
    path("webhooks/exotel/", views.exotel_webhook, name="exotel-webhook"),
]
