from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("integrations/hubspot/settings/", views.hubspot_settings, name="hubspot-settings"),
    path("integrations/hubspot/test/", views.test_hubspot_settings, name="test-hubspot-settings"),
    path(
        "integrations/hubspot/sync-call/<uuid:call_public_id>/",
        views.sync_call_to_hubspot,
        name="sync-call-to-hubspot",
    ),
    path("settings/exotel/wait-audio/", views.get_exotel_wait_audio, name="get-exotel-wait-audio"),
    path("settings/exotel/wait-audio/upload/", views.upload_exotel_wait_audio, name="upload-exotel-wait-audio"),
    path("settings/exotel/wait-audio/clear/", views.clear_exotel_wait_audio, name="clear-exotel-wait-audio"),
    path("agents/", views.list_agents, name="list-agents"),
    path("agents/create/", views.create_agent, name="create-agent"),
    path("agents/<int:agent_id>/update/", views.update_agent, name="update-agent"),
    path("agents/<int:agent_id>/delete/", views.delete_agent, name="delete-agent"),
    path("agents/<int:agent_id>/status/", views.update_agent_status, name="update-agent-status"),
    path("campaigns/", views.list_campaigns, name="list-campaigns"),
    path("campaigns/create/", views.create_campaign, name="create-campaign"),
    path("campaigns/<int:campaign_id>/", views.get_campaign, name="get-campaign"),
    path("campaigns/<int:campaign_id>/delete/", views.delete_campaign, name="delete-campaign"),
    path("campaigns/<int:campaign_id>/analytics/", views.campaign_analytics, name="campaign-analytics"),
    path("campaigns/<int:campaign_id>/queue/", views.campaign_queue, name="campaign-queue"),
    path("campaigns/<int:campaign_id>/timeline/", views.campaign_timeline, name="campaign-timeline"),
    path("campaigns/<int:campaign_id>/timeline/clear/", views.clear_campaign_timeline, name="clear-campaign-timeline"),
    path("campaigns/timeline/clear-all/", views.clear_all_campaign_timelines, name="clear-all-campaign-timelines"),
    path("campaigns/<int:campaign_id>/start/", views.start_campaign, name="start-campaign"),
    path("campaigns/<int:campaign_id>/pause/", views.pause_campaign, name="pause-campaign"),
    path("campaigns/<int:campaign_id>/resume/", views.resume_campaign, name="resume-campaign"),
    path("campaigns/<int:campaign_id>/stop/", views.stop_campaign, name="stop-campaign"),
    path(
        "campaigns/<int:campaign_id>/restart-from-first/",
        views.restart_campaign_from_first,
        name="restart-campaign-from-first",
    ),
    path("campaigns/<int:campaign_id>/dispatch/", views.dispatch_campaign, name="dispatch-campaign"),
    path("campaigns/<int:campaign_id>/tick/", views.campaign_tick, name="campaign-tick"),
    path(
        "campaigns/<int:campaign_id>/contacts/<int:lead_id>/remove/",
        views.remove_campaign_contact,
        name="remove-campaign-contact",
    ),
    path("leads/", views.list_leads, name="list-leads"),
    path("leads/<int:lead_id>/update/", views.update_lead, name="update-lead"),
    path("leads/<int:lead_id>/delete/", views.delete_lead, name="delete-lead"),
    path("leads/bulk-delete/", views.bulk_delete_leads, name="bulk-delete-leads"),
    path("leads/bulk-delete-filtered/", views.bulk_delete_filtered_leads, name="bulk-delete-filtered-leads"),
    path("contacts/", views.list_contacts, name="list-contacts"),
    path("leads/next/", views.next_lead, name="next-lead"),
    path("leads/upload/", views.upload_leads_csv, name="upload-leads-csv"),
    path("leads/manual/", views.create_manual_leads, name="create-manual-leads"),
    path("call-logs/", views.list_call_logs, name="list-call-logs"),
    path("recordings/", views.list_recordings, name="list-recordings"),
    path("recordings/upload/", views.upload_recording, name="upload-recording"),
    path("recordings/<uuid:recording_public_id>/", views.get_recording, name="get-recording"),
    path("recordings/<uuid:recording_public_id>/transcribe/", views.transcribe_recording, name="transcribe-recording"),
    path("calls/<uuid:call_public_id>/", views.get_call_session, name="get-call-session"),
    path("calls/<uuid:call_public_id>/hangup/", views.hangup_call_session, name="hangup-call-session"),
    path("calls/<uuid:call_public_id>/disposition/", views.save_call_disposition, name="save-call-disposition"),
    path("call-logs/sync/exotel/", views.sync_exotel_call_logs, name="sync-exotel-call-logs"),
    path(
        "call-logs/<int:call_id>/trigger_transcription/",
        views.trigger_transcription,
        name="trigger-transcription",
    ),
    path("calls/start/exotel/", views.start_exotel_call, name="start-exotel-call"),
    path("webhooks/exotel/", views.exotel_webhook, name="exotel-webhook"),
]
